name: CI
on:
  - pull_request
  - push

jobs:
  test-ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu-utils
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils

      - uses: actions/checkout@v4

      - name: Build image for x86_64 with BIOS mode and without GPT
        run: |
          sudo ./alpine-make-vm-image \
              --image-format qcow2 \
              --image-size 2G \
              --repositories-file example/repositories \
              --packages "$(cat example/packages)" \
              --fs-skel-dir example/rootfs \
              --fs-skel-chown root:root \
              --script-chroot \
              alpine-bios-$(date +%Y-%m-%d).qcow2 -- ./example/configure.sh

      - name: Build image for x86_64 with BIOS mode and GPT
        run: |
          sudo ./alpine-make-vm-image \
              --image-format raw \
              --image-size 2G \
              --partition \
              --repositories-file example/repositories \
              --packages "$(cat example/packages)" \
              --fs-skel-dir example/rootfs \
              --fs-skel-chown root:root \
              --script-chroot \
              alpine-bios-part-$(date +%Y-%m-%d).raw -- ./example/configure.sh

  test-alpine:
    name: Test on Alpine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # We must run this outside the chroot.
      - run: sudo modprobe nbd max_part=16

      - name: Set up latest Alpine Linux
        uses: jirutka/setup-alpine@v1

      - name: Build image for x86_64 with BIOS mode and without GPT
        run: |
          ./alpine-make-vm-image \
              --image-format qcow2 \
              --image-size 2G \
              --repositories-file example/repositories \
              --packages "$(cat example/packages)" \
              --fs-skel-dir example/rootfs \
              --fs-skel-chown root:root \
              --script-chroot \
              alpine-bios-$(date +%Y-%m-%d).qcow2 -- ./example/configure.sh
        shell: alpine.sh --root {0}
